# Generated by Django 5.0.2 on 2024-04-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
