# Generated by Django 5.0.2 on 2024-05-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_person_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='enroll_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='blog.courses'),
        ),
    ]
